### ISSUE TITLE
投稿参照記法

### ISSUE THREAD

**Issue by rinsuki** [linkage-community/bottlemail-preset-sea#1]
`>>1` のような感じで投稿を参照できるようにしたい

## 必要な物

- 投稿への返信記法 `>>\d+` (`>>0123`のような0始まりは許容しなくてもいいかも)
- ~~投稿参照記法 (要検討)~~ `/posts/:id` のリンクを貼るという形で決着

**Comment by otofune** [comment]
https://github.com/linkage-community/bottlemail/issues/59 でカスタムルール実装できるようになったらやっていきたい

**Comment by rinsuki** [comment]
返信は inReplyToで指定することにしたので close 🤐

**Comment by otofune** [comment]
絶対に正しい、それで

**Comment by otofune** [comment]
リプライボタンを押したら出るべき、そう
